import type { NextPage } from "next";
import Head from "next/head";

import React, { useEffect, useState } from "react";
import styled, { ThemeProvider } from "styled-components";
import { darkTheme, lightTheme } from "../styles/themes";
import { GlobalStyles } from "../styles/global.styles";
import { useDarkMode } from "../utilities/hooks/darkMode";

import Header from "../components/header";
import SearchInput from "../components/searchInput";
import FilterDropDown from "../components/filterDropDown";
import TestComponent from "./test";

// fetch data
const defaultEndpoint = "https://restcountries.com/v3.1/all";
export const getServerSideProps = async () => {
  try {
    const res = await fetch(defaultEndpoint);
    const data = await res.json();
    return { props: {data}}
  } catch (err) {
    console.log(err)
  }
};
interface Props {
  data: [];
}
const Home: NextPage<Props> = ({ data }) => {
  const [fetchedData] = useState(data)
  console.log(fetchedData)
  const [theme, themeToggler, mountedComponent] = useDarkMode();
  const themeMode = theme === "light" ? lightTheme : darkTheme;

  useEffect(() => {}, []);
  if (!mountedComponent) return <div />;
  return (
    <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
      <>
        <GlobalStyles />
        <Head>
          <title>Where in the World</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon-32x32.png" />
        </Head>
        <Header
          title={"Where in the world?"}
          theme={theme}
          toggleTheme={themeToggler}
          themeMode={themeMode}
        />
        <main>
          <MainContainer>
            <TopMainContainer>
              <SearchInput />
              <FilterDropDown title={"Filter by Region"} size={"small"} />
            </TopMainContainer>
            <BottomMainContainer>
              <TestComponent data={fetchedData} />
            </BottomMainContainer>
          </MainContainer>

          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </main>
      </>
    </ThemeProvider>
  );
};

export default Home;
const BottomMainContainer = styled.div``;
const TopMainContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
`;
const MainContainer = styled.div``;
